### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by csandanov** [drupal-composer/preserve-paths#28] opened 2019-12-03 04:52 UTC
Hi, setting up Drupal 7 via composer with PHP 7.4 currently fails with the following error:

```shell
$ composer -v create-project drupal-composer/drupal-project:7.x-dev some-dir --no-interaction
Installing drupal-composer/drupal-project (7.x-dev 267d7fe14c74af8c04fc84c7f483434eca35ef90)
  - Installing drupal-composer/drupal-project (7.x-dev 267d7fe): Cloning 267d7fe14c74af8c04fc84c7f483434eca35ef90 from cache
Created project in some-dir
> pre-update-cmd: DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.255 seconds
Analyzed 6353 packages to resolve dependencies
Analyzed 403588 rules to resolve dependencies
Package operations: 29 installs, 0 updates, 0 removals
Installs: composer/installers:v1.7.0, cweagans/composer-patches:1.6.7, drupal-composer/preserve-paths:0.1.5, composer/semver:1.5.0, drupal/drupal:7.67.0, drupal/composer_autoloader:1.3.0, symfony/polyfill-ctype:v1.13.1, webmozart/assert:1.6.0, webmozart/path-util:2.3.0, webflo/drupal-finder:1.2.0, pear/console_table:v1.3.1, symfony/finder:v3.4.36, symfony/event-dispatcher:v3.4.36, psr/log:1.1.2, symfony/debug:v4.4.1, symfony/polyfill-mbstring:v1.13.1, symfony/console:v3.4.36, symfony/var-dumper:v3.4.36, symfony/yaml:v3.4.36, dflydev/dot-access-data:v1.1.0, consolidation/output-formatters:3.5.0, consolidation/annotated-command:2.12.0, jakub-onderka/php-console-color:v0.2, jakub-onderka/php-console-highlighter:v0.4, dnoegel/php-xdg-base-dir:0.1, nikic/php-parser:v4.3.0, psy/psysh:v0.9.11, drush/drush:8.3.2, symfony/filesystem:v3.4.36
  - Installing composer/installers (v1.7.0): Downloading (100%)
 Extracting archive  - Installing cweagans/composer-patches (1.6.7): Downloading (100%)
 Extracting archiveNo patches found for cweagans/composer-patches.
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
Found 1 patches for cweagans/composer-patches.
  - Installing drupal-composer/preserve-paths (0.1.5): Downloading (100%)
 Extracting archiveNo patches found for drupal-composer/preserve-paths.


  [ErrorException]
  Trying to access array offset on value of type null


Exception trace:
 () at /var/www/html/some-dir/vendor/drupal-composer/preserve-paths/src/PluginWrapper.php:88
 Composer\Util\ErrorHandler::handle() at /var/www/html/some-dir/vendor/drupal-composer/preserve-paths/src/PluginWrapper.php:88
 DrupalComposer\PreservePaths\PluginWrapper->postPackage() at /var/www/html/some-dir/vendor/drupal-composer/preserve-paths/src/Plugin.php:69
 DrupalComposer\PreservePaths\Plugin->postPackage() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:176
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:116
 Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() at phar:///usr/local/bin/composer/src/Composer/Installer.php:622
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:229
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:195
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:145
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

```

**Comment by mtwango** [comment] 2019-12-09 11:17
What version of composer do you have? It should have been resolved in 1.9.1 update from 01-11-2019 (I had issues with 7.4RC versions of PHP)

**Comment by csandanov** [comment] 2019-12-09 12:12
```
Composer version 1.9.1 2019-11-01 17:20:17
```
the problem is still there

**Comment by Arkener** [comment] 2019-12-19 21:58
The issue is that the postPackage callback is triggered while this package itself is being installed, the prePackage isn't triggered in this case, as the package isn't available yet. This in turn will result in an error on PHP7.4 while retrieving the values from the preservers list, as it will be uninitialized.

**Comment by claylibrarymarket** [comment] 2020-04-20 13:42
I'm still encountering this issue.

**Closed** 2020-04-29 20:05 UTC

**Comment by uniquename** [comment] 2020-05-11 14:36
Not sure if this is really closed, because the fix is not in new version. 0.1.5 still contains the old code.

**Comment by AlexSkrypnyk** [comment] 2020-05-23 04:13
@derhasi 
Could we please have a release for this 🙏 
This currently breaks many build systems that are trying to use PHP 7.4.

**Comment by jackthomasatl** [comment] 2020-06-16 16:50
Yea, can someone build this already or is this package abandoned?

**Comment by jonpugh** [comment] 2020-08-06 16:00
Submitting a PR to drupal-composer/drupal-project to update the package to the SHA until we get a new tag.

**Comment by L0rD59** [comment] 2020-12-04 14:17
The new release do the job ! https://github.com/drupal-composer/preserve-paths/releases/tag/0.1.6 :+1:
